# Generated by Django 2.1 on 2020-08-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alfa', '0003_auto_20200813_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='documento',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='nome',
            field=models.CharField(default='Arquivo', max_length=200),
        ),
    ]
